apiVersion: apps/v1
kind: Deployment
metadata:
  name: 2048-dep
  namespace: epquito-2048
spec:
  replicas: 1
  selector:
    matchLabels:
      app: 2048-dep
  template:
    metadata:
      labels:
        app: 2048-dep
    spec:
      containers:
      - name: 2048-dep
        image: epquito/epquito-2048:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        readinessProbe:
          httpGet:
            path: /
            port: 80
          successThreshold: 5
          periodSeconds: 5
        ports:
        - containerPort: 80
