apiVersion: v1
kind: Service
metadata:
  name: app-2048
  namespace: epquito-2048
spec:
  selector:
    app: 2048-dep
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
   