name: epquito-2048-cicd 
on: 
  push:
    branches:
      - master
env:
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  AWS_REGION: ${{ secrets.AWS_REGION}}

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
      - name: checkout repo 
        uses: actions/checkout@v2 
        with:
          ref: master

      - name: set up docker buildx
        uses: docker/setup-buildx-action@v1 

      - name: login to docker hub
        uses: docker/login-action@v1 
        with:
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ env.DOCKER_PASSWORD }}

      - name: build and push docker image
        uses: docker/build-push-action@v2 
        with:
          context: .
          push: true
          tags: ${{ env.DOCKER_USERNAME }}/2048:latest

  eks_deploy:
    needs: build_and_push
    runs-on: ubuntu-latest

    steps:
      - name: checkout repo 
        uses: actions/checkout@v2
        with:
          ref: master

      - name: configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1 
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Update kubeconfig for EKS
        run: |
          aws eks update-kubeconfig --name my-demo-cluster --kubeconfig ./kubeconfig.yml
          echo "KUBECONFIG=$(pwd)/kubeconfig.yml" >> $GITHUB_ENV

      - name: deploy to eks 
        run: |
          kubectl apply -f NameSpace/ 

      - name: deploy to eks 
        run: |
          kubectl apply -f 2048_dep/ 

